#!/bin/sh
set -e

case "$1" in
    purge)
        if getent passwd bc-vigil >/dev/null; then
            deluser --system bc-vigil 2>/dev/null || true
        fi
        rm -rf /var/lib/bc-vigil
        rm -rf /etc/bc-vigil
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
